// This file was generated by generate.py

#include "Metadata.h"

static const char* const names[] = {
    "Serial Number",
    "Hardware Version",
    "Firmware Version",
    "Device Name",
    "Serial Enabled",
    "Serial Baud Rate",
    "Serial RTS/CTS Enabled",
    "Binary Mode Enabled",
    "USB Data Messages Enabled",
    "Serial Data Messages Enabled",
    "Example Float",
};

static const char* const keys[] = {
    "serial_number",
    "hardware_version",
    "firmware_version",
    "device_name",
    "serial_enabled",
    "serial_baud_rate",
    "serial_rts_cts_enabled",
    "binary_mode_enabled",
    "usb_data_messages_enabled",
    "serial_data_messages_enabled",
    "example_float",
};

const MetadataType types[] = {
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeBool,
    MetadataTypeUint32,
    MetadataTypeBool,
    MetadataTypeBool,
    MetadataTypeBool,
    MetadataTypeBool,
    MetadataTypeFloat,
};

const size_t sizes[] = {
    sizeof (((Ximu3SettingsValues *) 0)->serialNumber),
    sizeof (((Ximu3SettingsValues *) 0)->hardwareVersion),
    sizeof (((Ximu3SettingsValues *) 0)->firmwareVersion),
    sizeof (((Ximu3SettingsValues *) 0)->deviceName),
    sizeof (((Ximu3SettingsValues *) 0)->serialEnabled),
    sizeof (((Ximu3SettingsValues *) 0)->serialBaudRate),
    sizeof (((Ximu3SettingsValues *) 0)->serialRtsCtsEnabled),
    sizeof (((Ximu3SettingsValues *) 0)->binaryModeEnabled),
    sizeof (((Ximu3SettingsValues *) 0)->usbDataMessagesEnabled),
    sizeof (((Ximu3SettingsValues *) 0)->serialDataMessagesEnabled),
    sizeof (((Ximu3SettingsValues *) 0)->exampleFloat),
};

const void* const defaults[] = {
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"x-IMU3 Device"}),
    (void*) (&(bool) {true}),
    (void*) (&(uint32_t) {115200}),
    (void*) (&(bool) {false}),
    (void*) (&(bool) {true}),
    (void*) (&(bool) {true}),
    (void*) (&(bool) {true}),
    (void*) (&(float) {1.0f}),
};

const bool preserveds[] = {
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
};

const bool readOnlys[] = {
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
};

static void* GetValue(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {
    switch (index) {
        case Ximu3SettingsIndexSerialNumber:
            return &settings->values.serialNumber;
        case Ximu3SettingsIndexHardwareVersion:
            return &settings->values.hardwareVersion;
        case Ximu3SettingsIndexFirmwareVersion:
            return &settings->values.firmwareVersion;
        case Ximu3SettingsIndexDeviceName:
            return &settings->values.deviceName;
        case Ximu3SettingsIndexSerialEnabled:
            return &settings->values.serialEnabled;
        case Ximu3SettingsIndexSerialBaudRate:
            return &settings->values.serialBaudRate;
        case Ximu3SettingsIndexSerialRtsCtsEnabled:
            return &settings->values.serialRtsCtsEnabled;
        case Ximu3SettingsIndexBinaryModeEnabled:
            return &settings->values.binaryModeEnabled;
        case Ximu3SettingsIndexUsbDataMessagesEnabled:
            return &settings->values.usbDataMessagesEnabled;
        case Ximu3SettingsIndexSerialDataMessagesEnabled:
            return &settings->values.serialDataMessagesEnabled;
        case Ximu3SettingsIndexExampleFloat:
            return &settings->values.exampleFloat;

    }
    return NULL; // avoid compiler warning
}

Metadata MetadataGet(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {
    const Metadata metaData = {
        .name = names[index],
        .key = keys[index],
        .value = GetValue(settings, index),
        .type = types[index],
        .size = sizes[index],
        .defaultValue = defaults[index],
        .preserved = preserveds[index],
        .readOnly = readOnlys[index],
        .applied = &settings->applied[index],
    };
    return metaData;
}
