// This file was generated by generate.py

#ifndef METADATA_H
#define METADATA_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "Ximu3Definitions.h"
#include "Ximu3Settings.h"

typedef enum {
    MetadataTypeBool,
    MetadataTypeCharArray,
    MetadataTypeFloat,
    MetadataTypeUint32,
} MetadataType;

typedef struct {
    const char* const name;
    const char* const key;
    void* const value;
    const MetadataType type;
    const size_t size;
    const void* const defaultValue;
    const bool preserved;
    const bool readOnly;
    bool* const applied;
} Metadata;

Metadata MetadataGet(Ximu3Settings * const settings, const Ximu3SettingsIndex index);

#endif
