// This file was generated by generate.py

#ifndef XIMU3_DEFINITIONS_H
#define XIMU3_DEFINITIONS_H

#include <stdbool.h>
#include <stdint.h>

#define XIMU3_KEY_SIZE 64

#define XIMU3_VALUE_SIZE 512

#define XIMU3_OBJECT_SIZE 1024

#define XIMU3_MAX_KEY_LENGTH 20

#define XIMU3_NUMBER_OF_SETTINGS 8

#define XIMU3_MUX_HEADER_SIZE 2

typedef enum {
    Ximu3ResultOk,
    Ximu3ResultError,
} Ximu3Result;

typedef struct {
    char serialNumber[16];
    char calibrationDate[32];
    float offset;
    float sensitivity;
    char firmwareVersion[32];
    char deviceName[32];
    bool binaryMode;
    uint32_t messageRateDivisor;
} Ximu3SettingsValues;

typedef enum {
    Ximu3SettingsIndexSerialNumber,
    Ximu3SettingsIndexCalibrationDate,
    Ximu3SettingsIndexOffset,
    Ximu3SettingsIndexSensitivity,
    Ximu3SettingsIndexFirmwareVersion,
    Ximu3SettingsIndexDeviceName,
    Ximu3SettingsIndexBinaryMode,
    Ximu3SettingsIndexMessageRateDivisor,
} Ximu3SettingsIndex;

Ximu3Result Ximu3SettingsIndexFrom(Ximu3SettingsIndex * const index, const int integer);

#endif
