// This file was generated by generate.py

#include "Ximu3Definitions.h"

Ximu3Result Ximu3SettingsIndexFrom(Ximu3SettingsIndex * const index, const int integer) {
    switch (integer) {
        case Ximu3SettingsIndexSerialNumber:
            *index = Ximu3SettingsIndexSerialNumber;
            break;
        case Ximu3SettingsIndexHardwareVersion:
            *index = Ximu3SettingsIndexHardwareVersion;
            break;
        case Ximu3SettingsIndexFirmwareVersion:
            *index = Ximu3SettingsIndexFirmwareVersion;
            break;
        case Ximu3SettingsIndexDeviceName:
            *index = Ximu3SettingsIndexDeviceName;
            break;
        case Ximu3SettingsIndexSerialEnabled:
            *index = Ximu3SettingsIndexSerialEnabled;
            break;
        case Ximu3SettingsIndexSerialBaudRate:
            *index = Ximu3SettingsIndexSerialBaudRate;
            break;
        case Ximu3SettingsIndexSerialRtsCtsEnabled:
            *index = Ximu3SettingsIndexSerialRtsCtsEnabled;
            break;
        case Ximu3SettingsIndexBinaryModeEnabled:
            *index = Ximu3SettingsIndexBinaryModeEnabled;
            break;
        case Ximu3SettingsIndexUsbDataMessagesEnabled:
            *index = Ximu3SettingsIndexUsbDataMessagesEnabled;
            break;
        case Ximu3SettingsIndexSerialDataMessagesEnabled:
            *index = Ximu3SettingsIndexSerialDataMessagesEnabled;
            break;
        case Ximu3SettingsIndexExampleFloat:
            *index = Ximu3SettingsIndexExampleFloat;
            break;
        default:
            return Ximu3ResultError;
    }
    return Ximu3ResultOk;
}
