/**
 * @file Led.c
 * @author Seb Madgwick
 * @brief LED driver.
 */

//------------------------------------------------------------------------------
// Includes

#include "definitions.h"
#include "Led.h"
#include "PeripheralBusClockFrequency.h"
#include "Pwm/Pwm4.h"
#include <stdbool.h>
#include <stdint.h>
#include "Timer/Timer.h"

//------------------------------------------------------------------------------
// Definitions

/**
 * @brief Blink state.
 */
typedef enum {
    BlinkStateIdle,
    BlinkStateBegin,
    BlinkStateEnd,
} BlinkState;

//------------------------------------------------------------------------------
// Function declarations

static inline __attribute__((always_inline)) void Update(void);

//------------------------------------------------------------------------------
// Variables

static BlinkState blinkState;
static uint64_t strobeTimeout;

//------------------------------------------------------------------------------
// Functions

/**
 * @brief Initialises the module. This function must only be called once, on
 * system startup.
 */
void LedInitialise(void) {

    // Initialise PWM
    Pwm4Initialise(0);

    // Configure state update timer
    CCP2CON1bits.T32 = 1;
    CCP2PR = PERIPHERAL_BUS_CLOCK_FREQUENCY / 10; // 10 Hz
    CCP2CON1bits.ON = 1;
    EVIC_SourceStatusClear(INT_SOURCE_CCT2);
    EVIC_SourceEnable(INT_SOURCE_CCT2);
}

/**
 * @brief CCT interrupt handler. This function should be called by the ISR
 * implementation generated by MPLAB Harmony.
 */
void Cct2InterruptHandler(void) {
    Update();
    EVIC_SourceStatusClear(INT_SOURCE_CCT2);
}

/**
 * @brief Update the LED.
 */
static inline __attribute__((always_inline)) void Update(void) {
    const uint16_t dimmed = 0x0000;
    const uint16_t normal = 0x1FFF;
    const uint16_t bright = 0xFFFF;

    // Strobe
    if (TimerGetTicks64() < strobeTimeout) {
        Pwm4Set(Pwm4Get() != dimmed ? dimmed : bright);
        return;
    }

    // Blink
    switch (blinkState) {
        case BlinkStateIdle:
            break;
        case BlinkStateBegin:
            Pwm4Set(bright);
            blinkState = BlinkStateEnd;
            return;
        case BlinkStateEnd:
            Pwm4Set(normal);
            blinkState = BlinkStateIdle;
            return;
    }

    // Normal
    Pwm4Set(normal);
}

/**
 * @brief Blinks the LED.
 */
void LedBlink(void) {
    const bool state = EVIC_INT_SourceDisable(INT_SOURCE_CCT2);
    switch (blinkState) {
        case BlinkStateIdle:
            blinkState = BlinkStateBegin;
            break;
        case BlinkStateBegin:
        case BlinkStateEnd:
            break;
    }
    EVIC_INT_SourceRestore(INT_SOURCE_CCT2, state);
}

/**
 * @brief Strobes the LED.
 */
void LedStrobe(void) {
    const bool state = EVIC_INT_SourceDisable(INT_SOURCE_CCT2);
    strobeTimeout = TimerGetTicks64() + (5 * TIMER_TICKS_PER_SECOND);
    EVIC_INT_SourceRestore(INT_SOURCE_CCT2, state);
}

//------------------------------------------------------------------------------
// End of file
